### ISSUE TITLE
Unhandled exception when accessing saves through JKSV

### ISSUE THREAD

**Issue by gh0stbyters** [lchmagKekse/TOTK-SaveGame-Editor#11]
![Untitled](https://github.com/lchmagKekse/TOTK-SaveGame-Editor/assets/133163389/670f16cc-6dc2-4d54-a390-768791d46583)

Tried running as admin, wont patch -shrug- Great job so far though you guys work fast!

EDIT: Also trying to access the file from my appdata which its not in there ?

**Comment by airainchoc** [comment]
Did you try copying it to a "real" folder on your pc ?
Assuming you try to access it directly on your switch

**Comment by gh0stbyters** [comment]
> Did you try copying it to a "real" folder on your pc ? Assuming you try to access it directly on your switch

You are a genius I am so dumb LMAO. Please excuse me ive been very sick and have flu brain. That seemed to do the trick.

**Comment by airainchoc** [comment]
No problem, glad it's working ;)
