### ISSUE TITLE
Editor ruined save file

### ISSUE THREAD

**Issue by mwhart88** [lchmagKekse/TOTK-SaveGame-Editor#14]
Used the editor to give myself 16 hearts, 3 stamina wheels, full Tunic of Twilight and a few bows and shields. Using this on Ryujinx switch emulator. After using this I went to manually save and the game got stuck in a indefinite save loop and I couldn't do anything but restart the emulator and now whenever I try to load the game it instantly crashes the emulator. Didn't do any of this beforehand.

**Comment by lchmagKekse** [comment]
Can you share your save folder so I can take a look what caused this?

Also I noticed when having the folder with the save game open Ryujinx isn't able to save. That might be the problem

**Comment by mwhart88** [comment]
Update: after I deleted the Ryujinx emulator I reinstalled the emulator and then use the save editor to give myself 16 Hearts Max stamina 10,000 rupees full tunic of Twilight Etc then I patched the save and made sure that there was nothing open in File Explorer nothing open in background programs before I opened tears of the Kingdom I am now successfully able to manually save without a indefinite save Loop and I am able to play the game without any problem so far I will update if I come across anything but so far everything is Peachy

**Comment by kilianpaquier** [comment]
Hey ! I noticed that Ryujinx end up in infinite loop if the folder with all the saves is opened in explorer when saving. Your issue may have come from that.
