### ISSUE TITLE
master sword

### ISSUE THREAD

**Issue by analyzecarbon** [lchmagKekse/TOTK-SaveGame-Editor#17]
Is it possible to create a Master Sword with damage buffs like Last Battle?Sorry for my poor English

**Comment by lchmagKekse** [comment]
What do you mean by Last Battle?

**Comment by analyzecarbon** [comment]
Probably like the previous work, I think that the master sword has a special damage buff only in the battle against Ganondorf.

**Comment by analyzecarbon** [comment]
item id Weapon_Sword_070_TrueForm_Attached

**Comment by valetzx** [comment]
![image](https://github.com/lchmagKekse/TOTK-SaveGame-Editor/assets/45054400/88946f0a-a1df-4dc0-8d3e-245297edfc7c)
your item `Weapon_Sword_070_TrueForm_Attached` only exists in data，include `Weapon_Sword_070_TrueForm` and `Weapon_Sword_070_Attached`

**Comment by analyzecarbon** [comment]
Thank you for looking into this. It doesn't seem to work.
