### ISSUE TITLE
durability?

### ISSUE THREAD

**Issue by djmatt18000** [lchmagKekse/TOTK-SaveGame-Editor#18]
is it possible to ad the ability to edit the durability of weapons shields and bows

**Comment by lchmagKekse** [comment]
I'm planing on adding this. However, durability has a limit for each weapon. If you go above that, the game will just reset it to the max value for that weapon.

**Comment by Squall-Leonhart** [comment]
> I'm planing on adding this. However, durability has a limit for each weapon. If you go above that, the game will just reset it to the max value for that weapon.

if its anything like the last game engine, a setting of 6553500 disables durability.
