### ISSUE TITLE
Nicht für den Pc?

### ISSUE THREAD

**Issue by Sekaj** [lchmagKekse/TOTK-SaveGame-Editor#25]
Hi

kann man das tool nicht am pc nutzen, oder braucht man zusätzliche software?  hab dort nur  .cs / .csprojj  / .resx   datein die ich nicht am pc starten kann.

Würde mich über hilfreiche antworten freuen
Grüße Sekaj

**Comment by JarFiles** [comment]
Du könntest dir das Projekt entweder selbst kompilieren, oder die schon kompilierte Anwendung bei den Releases runterladen

**Comment by Sekaj** [comment]
Danke dir, ich bin wohl noch zu blöd für github.  hab jetzt nochmal alles angeschaut und den Releases Bereich gefunden.    sry für den unnötigen Post von mir
