### ISSUE TITLE
Only 5 slots avalaible to edit 

### ISSUE THREAD

**Issue by iscomalha** [lchmagKekse/TOTK-SaveGame-Editor#26]
Idk if it's on purpose or is it just for me, but I only have 5 spots available to edit for weapons, shields, bows and equipment.

**Comment by metalsolid** [comment]
I was confused on that too.

**Comment by weiajingjing** [comment]
Me too, it makes me feel very confused

**Comment by Dantasstic** [comment]
I, too, am confused, and would like to edit _all the slots_ that any given section has available, especially because you cannot manually put items into the first five slots, you can only sort.
