### ISSUE TITLE
Game no longer saves after editing (the folder isn't open)

### ISSUE THREAD

**Issue by Nitobliss** [lchmagKekse/TOTK-SaveGame-Editor#27]

**Comment by lchmagKekse** [comment]
Can you share your save folder so I can look into this?

**Comment by wmeacham1** [comment]
Same thing happened to me with Ryu freezing when I went to save. I changed the permissions on the progress file to allow everyone and it seems to save and work now.

**Comment by bluedoom** [comment]
don't know what's going on. but delete the slot can let ryujinx save game while freezing.
