### ISSUE TITLE
Add change to save date 

### ISSUE THREAD

**Issue by Pa111o** [lchmagKekse/TOTK-SaveGame-Editor#28]
I was doing some editing with the saves and then notice on that the date was changed to 06/01/3172604 at 11 pm. Also i think would also be good for those who have amibo and did the date forwarding and want to set date back.
![2023051513140500-CC47F0DEC75C1FD3B1F95FA9F9D57667](https://github.com/lchmagKekse/TOTK-SaveGame-Editor/assets/133704504/1d77c0f7-c1c9-47ef-8126-9f39150c32fc)

**Comment by saucesome** [comment]
I ran into this without using this tool; not sure how to fix -- wasn't trying to do anything fishy but I noticed all my save dates are June 1st, 3172604 at 11:00 PM :|

**Comment by lchmagKekse** [comment]
@Pa111o @saucesome Are you both on emulator?

**Comment by Pa111o** [comment]
when I notice this I was playing on my cfw switch

**Comment by systox** [comment]
did you use any mods? On emulators, people are saying that those who played with older dynamic fps mods/60 fps mods borked their game times/more frequent blood moons/etc. It'd be nice if there was a fix.

**Comment by Pa111o** [comment]
no i havent installed any mods just installed the xci when it was leaked then switched to gamecard when the released day dropped
