### ISSUE TITLE
If you have purchased housing storage it changes what slot is being edited. 

### ISSUE THREAD

**Issue by Bilwits** [lchmagKekse/TOTK-SaveGame-Editor#6]
I believe this is caused by buying the house and storage units. Weapons, Bows, and Shields will edit whats placed in storage. You can no longer edit armor.

**Comment by lchmagKekse** [comment]
Can you share your progress.sav? I will take a look at this after work

**Comment by Bilwits** [comment]
https://file.io/18GqpP7cWuos

**Comment by lchmagKekse** [comment]
@Bilwits I cant download the file
![image](https://github.com/lchmagKekse/TOTK-SaveGame-Editor/assets/44001978/f7624d92-40ef-4972-8469-e7bde913a707)

Can you zip it and upload it here?
Also what version of the game are you playing? 1.0.0 or 1.1.0?

**Comment by Bilwits** [comment]
[slot_01.zip](https://github.com/lchmagKekse/TOTK-SaveGame-Editor/files/11444617/slot_01.zip) 1,1

**Comment by lchmagKekse** [comment]
Thank you, the newest release should fix this issue:
https://github.com/lchmagKekse/TOTK-SaveGame-Editor/releases/tag/v1.1.2
